name: Build and Deploy to Docker Hub

on: 
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: 'ubuntu-latest'
        steps:
            - name: Check out Repo
              uses: actions/checkout@v2
            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Docker image
              uses: docker/build-push-action@v2
              with: 
                context: .
                file: ./docker/dockerfile.user
                push: true
                tags: aakarshbeohar/payme-client:latest

            - name: Verify pushed image
              run: docker pull aakarshbeohar/payme-client:latest
            
            - name: Deploy to EC2
              uses: applyboy/ssh-action@v1.2.0
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                script: |
                  sudo docker pull aakarshbeohar/payme-client:latest
                  sudo docker stop payme-client || true
                  sudo docker rm payme-client || true
                  sudo docker run -d --name payme-client -p 3005:3000 aakarshbeohar/payme-client:latest